const { chromium } = require('/Users/hbm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light',reducedMotion:'reduce'});
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.goto('http://127.0.0.1:4175/round-3/');
 await page.evaluate(() => document.fonts.ready);
 await page.screenshot({path:path.join(__dirname,'home-light.png')});
 await page.screenshot({path:path.join(__dirname,'home-full.png'),fullPage:true});
 assert.equal(await page.locator('.scroll-painting img').evaluate(el=>el.complete&&el.naturalWidth>0),true);
 assert.equal(await page.locator('canvas').count(),0);
 await page.locator('.theme-toggle').click();
 await page.screenshot({path:path.join(__dirname,'home-dark.png')});
 await page.getByRole('link',{name:'Notes',exact:true}).click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.locator('.theme-toggle').click();
 await page.screenshot({path:path.join(__dirname,'notes-light.png')});
 await page.reload(); assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.getByRole('link',{name:'Home',exact:true}).click();
 assert.equal(await page.locator('.uniform-project').count(),6);
 assert.equal(await page.evaluate(()=>Boolean(document.querySelector('.background').compareDocumentPosition(document.querySelector('#projects')) & Node.DOCUMENT_POSITION_FOLLOWING)),true);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'home-mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('link',{name:'Notes',exact:true}).click();
 await page.screenshot({path:path.join(__dirname,'notes-mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({passed:['landscape image loaded','no orbit hero','theme across pages and reload','six consistent project entries','background before projects','mobile no overflow','no script errors'],errors},null,2));
 await browser.close(); console.log('Round 3 prototype checks passed.');
})().catch(e=>{console.error(e);process.exit(1)});
