const {chromium}=require('/Users/hbm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100},colorScheme:'light',reducedMotion:'reduce'});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4175/round-2/');
 await page.evaluate(()=>document.fonts.ready);
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.screenshot({path:path.join(__dirname,'light.png')});
 const initial=await page.locator('canvas').evaluate(el=>el.toDataURL());
 await page.locator('#play').click();await page.waitForTimeout(350);
 await page.locator('#play').click();
 assert.notEqual(await page.locator('canvas').evaluate(el=>el.toDataURL()),initial);
 await page.locator('#speed').fill('0.5');
 assert.equal(await page.locator('#speed-value').innerText(),'0.5×');
 await page.locator('#reset').click();
 assert.equal(await page.locator('#speed').inputValue(),'1');
 assert.equal(await page.locator('#play').getAttribute('aria-pressed'),'false');
 assert.equal(await page.locator('canvas').evaluate(el=>el.toDataURL()),initial);
 await page.locator('#theme').click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.reload();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.screenshot({path:path.join(__dirname,'dark.png')});
 await page.locator('#source-toggle').click();
 assert.equal(await page.locator('#source-panel').isVisible(),true);
 assert.match(await page.locator('#source-panel code').innerText(),/component: three-body/);
 await page.screenshot({path:path.join(__dirname,'source.png')});
 await page.locator('#source-toggle').click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'mobile-dark.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#theme').click();
 await page.screenshot({path:path.join(__dirname,'mobile-light.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({passed:['system light default','canvas changes during playback','pause','speed label','reset restores initial image and speed','dark preference persists on reload','Markdown source toggle','mobile light/dark no horizontal overflow'],pageErrors:errors},null,2));
 await browser.close();console.log('All review prototype checks passed.');
})().catch(e=>{console.error(e);process.exit(1)});
